#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PractDemo_001.Resource", IsApplication=true)]

namespace PractDemo_001
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int button = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int nofitication01 = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Avataricon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Avataricon_edited_01 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_pulldown_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_pulldown_icon_usd = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int EditText = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int IDicon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int IDicon_edited01 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int IDicon_uncheck = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int main_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int MrOBM = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int picturesource_line = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pulldown_cmttextbox = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pulldown_Genre_select = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int pulldown_imgbackground = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int warning_text = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060014
			public const int Button_submit = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int TextView_nofi01 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int TextView_nofi02 = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int TextView_nofi03 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int TextView_nofi04 = 2131099659;
			
			// aapt resource value: 0x7f06001c
			public const int btn_extraspinner = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int checkBox1 = 2131099673;
			
			// aapt resource value: 0x7f060025
			public const int editxt_pulldowncmtbox = 2131099685;
			
			// aapt resource value: 0x7f060015
			public const int imgv_checkboxicon = 2131099669;
			
			// aapt resource value: 0x7f06001d
			public const int imgv_extraspinner = 2131099677;
			
			// aapt resource value: 0x7f06000f
			public const int imgv_line00 = 2131099663;
			
			// aapt resource value: 0x7f06001b
			public const int imgv_line01 = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int imgv_line02 = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int imgv_line03 = 2131099661;
			
			// aapt resource value: 0x7f060013
			public const int imgv_line04 = 2131099667;
			
			// aapt resource value: 0x7f06001e
			public const int imgv_linepulldown01 = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int imgv_linepulldown02 = 2131099680;
			
			// aapt resource value: 0x7f060022
			public const int imgv_linepulldown03 = 2131099682;
			
			// aapt resource value: 0x7f060016
			public const int imgv_scrname = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int imgv_usrid = 2131099671;
			
			// aapt resource value: 0x7f06001f
			public const int imgvbtn_pulldownimg = 2131099679;
			
			// aapt resource value: 0x7f060028
			public const int spn_pulldownspinnergeneralselect01 = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int spn_pulldownspinnergeneralselect02 = 2131099689;
			
			// aapt resource value: 0x7f06001a
			public const int spn_pulldownspinnergeneralselect03 = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int textView1 = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int textView10 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int textView11 = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int textView13 = 2131099662;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int textView3 = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int textView3b = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int textView4 = 2131099654;
			
			// aapt resource value: 0x7f06000c
			public const int textView7 = 2131099660;
			
			// aapt resource value: 0x7f060012
			public const int textView9 = 2131099666;
			
			// aapt resource value: 0x7f060002
			public const int txtpln_screenName = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int txtpln_userID = 2131099656;
			
			// aapt resource value: 0x7f060018
			public const int txtv_checkbox = 2131099672;
			
			// aapt resource value: 0x7f060023
			public const int txtv_imgbox = 2131099683;
			
			// aapt resource value: 0x7f060021
			public const int txtv_pulldowncmtlabel = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int txtv_pulldowncmttittle = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int txtv_pulldowngeneralselect_require = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int txtv_pulldowngeneralselect_tittle = 2131099686;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050010
			public const int btn_pulldown = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int button_submit = 2131034127;
			
			// aapt resource value: 0x7f050006
			public const int edittext_id = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int edittext_screenname = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int require = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int textview1 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int textview_id = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textview_nofitication1 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int textview_nofitication2 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textview_nofitication3 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textview_nofitication4 = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int textview_privacylink1 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int textview_privacylink2 = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int textview_pulldown_cmttittle = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int textview_pulldown_generalselectiontittle = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int textview_pulldown_generalselectiontittle_require = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int textview_pulldown_imgtitle = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int textview_screenname = 2131034115;
			
			// aapt resource value: 0x7f05000c
			public const int textview_userimg = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int textview_warning1 = 2131034121;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
